//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdopcionEstado
    {
        public int Id { get; set; }
        public int adopcionId { get; set; }
        public int estadoId { get; set; }
    
        public virtual Adopcion Adopcion { get; set; }
        public virtual Estado Estado { get; set; }
    }
}
