//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudio
    {
        public int Id { get; set; }
        public int mascotaId { get; set; }
        public int tipoEstudioId { get; set; }
        public System.DateTime fecha_realizacion { get; set; }
        public Nullable<int> veterinarioId { get; set; }
        public Nullable<System.DateTime> fecha_vencimiento { get; set; }
        public string observaciones { get; set; }
    
        public virtual Mascota Mascota { get; set; }
        public virtual TipoEstudio TipoEstudio { get; set; }
        public virtual Veterinario Veterinario { get; set; }
    }
}
