//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mascota
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mascota()
        {
            this.Adopcion = new HashSet<Adopcion>();
            this.Donacion = new HashSet<Donacion>();
            this.Estudio = new HashSet<Estudio>();
            this.Multimedia = new HashSet<Multimedia>();
            this.Visita = new HashSet<Visita>();
        }
    
        public int Id { get; set; }
        public Nullable<int> razaId { get; set; }
        public string nombre { get; set; }
        public string sexo { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
                
        public string edad
        {
            get
            {
                int dias = (int)(DateTime.Today - fecha_nacimiento.Value).TotalDays;
                int años = dias / 365;
                int meses = (dias % 365) / 31;

                switch (años)
                {
                    case 0: return string.Format("{0} Meses", meses);
                    case 1: return string.Format("{0} Año", años);
                    default: return string.Format("{0} Años", años);
                }
            }
        }

        public string color { get; set; }
        public Nullable<int> tamañoId { get; set; }
        public string caracter { get; set; }
        public string observaciones { get; set; }
        public string avatar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adopcion> Adopcion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donacion> Donacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estudio> Estudio { get; set; }
        public virtual Raza Raza { get; set; }
        public virtual Tamaño Tamaño { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Multimedia> Multimedia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visita> Visita { get; set; }
    }
}
