//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Multimedia
    {
        public int Id { get; set; }
        public int mascotaId { get; set; }
        public string tipo_archivo { get; set; }
        public string ruta { get; set; }
        public Nullable<System.DateTime> fecha_publicacion { get; set; }
    
        public virtual Mascota Mascota { get; set; }
    }
}
